# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/buoy.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'proto/buoy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/buoy.proto\x12\x04\x62uoy\"\xe6\x01\n\nBuoyStatus\x12\x0f\n\x07\x62uoy_id\x18\x01 \x01(\x04\x12\x11\n\treport_id\x18\x02 \x01(\x04\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x10\n\x08latitude\x18\x04 \x01(\x01\x12\x11\n\tlongitude\x18\x05 \x01(\x01\x12\x14\n\x0c\x64\x65pth_meters\x18\x06 \x01(\x01\x12\x14\n\x0ctemp_celsius\x18\x07 \x01(\x01\x12\x0f\n\x07\x61\x63\x63\x65l_x\x18\x08 \x01(\x01\x12\x0f\n\x07\x61\x63\x63\x65l_y\x18\t \x01(\x01\x12\x0f\n\x07\x61\x63\x63\x65l_z\x18\n \x01(\x01\x12\x1d\n\x15\x62\x61ttery_level_percent\x18\x0b \x01(\x05\x42\x0fZ\rbuoyboy/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.buoy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rbuoyboy/proto'
  _globals['_BUOYSTATUS']._serialized_start=27
  _globals['_BUOYSTATUS']._serialized_end=257
# @@protoc_insertion_point(module_scope)
