[project]
name = "simbuoy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "protobuf>=5.29.3",
]

[dependency-groups]
dev = []
